source 'https://github.com/CocoaPods/Specs.git'

target 'ReadLess' do
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end

# Start the React Native JS packager server when running the project in Xcode.
